In [4]:
import numpy as np
import pandas as pd

In [5]:
flates=pd.read_csv('flats_cleaned.csv')
houses=pd.read_csv('house_cleaned.csv')

In [7]:
df=pd.concat([flates,houses],ignore_index=True)

In [12]:
df.sample(df.shape[0])

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2474,4 Bedroom House for sale in Maruti Kunj,house,independent,0.70,4117.0,1700.000000,Plot area 1700(157.94 sq.m.),4,4,1,not available,"Maruti Kunj, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,Interested to sell independent house/villa.It ...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2418,3 BHK Flat in Sector 79 Gurgaon,flat,bestech altura,1.72,8400.0,2047.619048,Built Up area: 2050 (190.45 sq.m.),3,4,3,not available,"Sector 79 Gurgaon, Gurgaon, Haryana",9.0,East,0 to 1 Year Old,"['Sapphire 83 Mall', 'NH -8', 'Golf Course Ext...",Pros of this unit \n1) corner unit ( Full priv...,"['4 Fan', '4 Geyser', '5 AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5..."
1576,12 Bedroom House for sale in Uppals Southend,house,uppal southend,6.75,290948.0,232.000000,Plot area 232(21.55 sq.m.),12,12,3+,"pooja room,study room,servant room,others","Uppals Southend, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
306,4 BHK Flat in Sector 113 Gurgaon,flat,m3m capital,2.90,12619.0,2298.121880,Carpet area: 2298 (213.49 sq.m.),4,4,3+,"study room,servant room","Sector 113 Gurgaon , Gurgaon, Haryana",11.0,North,Jan 2025,"['Phase 2 Metro Station', 'Global Foyer Mall',...","It's in tower 6c, corner unit and golf facing....",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
3532,14 Bedroom House for sale in DLF Phase 3,house,independent,3.20,59259.0,540.000000,Plot area 60(50.17 sq.m.),14,14,3+,not available,"Three Side Corner, DLF Phase 3, Gurgaon, Haryana",6.0,West,1 to 5 Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Rental income option for sale in 60 sq.Yds. Fu...,"['14 Bed', '14 Wardrobe', '1 Water Purifier', ...","['Water Storage', 'Park']","['Environment4 out of 5', 'Lifestyle5 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2963,16 Bedroom House for sale in Sector 40 Gurgaon,house,independent,12.00,38986.0,3078.000000,Plot area 342(285.96 sq.m.),16,16,3+,"pooja room,study room,servant room,store room","Sector 40 Gurgaon, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ready to move in simplex kothi available for s...,"['20 Wardrobe', '24 Fan', '18 Geyser', '99 Lig...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2498,4 BHK Flat in Sector 82A Gurgaon,flat,vatika sovereign next sector-82 a gurgaon,2.91,6700.0,4343.283582,Super Built up area 4350(404.13 sq.m.)Carpet a...,4,4,3,"study room,servant room,store room","Tower - K, Sector 82A Gurgaon, Gurgaon, Haryana",6.0,East,Under Construction,"['S.R.S. Hospital and Critical Care Unit', 'Or...",Penthouse prime location vatika sovereign next...,"['4 Wardrobe', '1 Exhaust Fan', '1 Modular Kit...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1426,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc 2,1.07,5246.0,2039.649257,Built Up area: 2040 (189.52 sq.m.),4,3,3,"study room,servant room",Green Parc-2 Cresent Patiolies Flat P-04-1001 ...,10.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Green parc-2Cresent patioliesFlat p-04-10014bh...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'I...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1586,3 Bedroom House for sale in Sector 23A Gurgaon,house,independent,1.20,6230.0,1926.000000,Plot area 214(178.93 sq.m.)Built Up area: 1500...,3,2,2,not available,"Sector 23, Sector 23A Gurgaon, Gurgaon, Haryana",3.0,NaN,0 to 1 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Property sale in huda sector 23a plot size 212...,"['5 Fan', '1 Exhaust Fan', '2 Geyser', '1 Micr...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1213,4 BHK Flat in Sector 81 Gurgaon,flat,bestech park view grand spa,4.00,9523.0,4200.357030,Super Built up area 4200(390.19 sq.m.),4,5,3+,servant room,"Sector-81, Sector 81 Gurgaon, Gurgaon, Haryana",15.0,West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...",This lovely 4 bhk apartment/flat in sector 81 ...,"['7 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."

In [9]:
df=df.sample(df.shape[0],ignore_index=True) #to remove the biasness from the dataset

In [13]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in DLF Phase 3,flat,dlf city plots phase 3,6.50,18571.0,3500.080771,Carpet area: 3500 (325.16 sq.m.),4,5,3+,servant room,"T8-3, DLF Phase 3, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Vastu perfect and overlooking beautiful orname...,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 109 Gurgaon,flat,brisk lumbini terrace homes,1.50,6616.0,2267.230955,Carpet area: 2267 (210.61 sq.m.),3,3,1,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Ram Mandir', 'K...",One of the best location of dwarka expressway,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
2,3 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,1.71,12000.0,1425.000000,Built Up area: 1423 (132.2 sq.m.),3,2,0,not available,"Sector 89, Sector 89 Gurgaon, Gurgaon, Haryana",3.0,NaN,undefined,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",3bhk multistorey apartment for resale in smart...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3,4 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.65,7449.0,2215.062424,Super Built up area 2215(205.78 sq.m.)Built Up...,4,4,3+,not available,"1256, Sector 90 Gurgaon, Gurgaon, Haryana",15.0,East,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",This 4 bhk apartment is available for sale in ...,"['1 Exhaust Fan', '4 Geyser', '10 Light', '6 A...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,5 Bedroom House for sale in Sector 111 Gurgaon,house,puri diplomatic greens,9.00,11250.0,8000.000000,Built Up area: 8000 (743.22 sq.m.),5,5,3+,servant room,"A1212, Sector 111 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Puri diplomatic greens\r\nPuri diplomatic gree...,"['4 Light', '6 AC', 'No Bed', 'No Chimney', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN