In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [2]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\user\anaconda3\lib\site-packages (3.1.3)
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\user\anaconda3\lib\site-packages (from xgboost) (1.15.3)

In [3]:
df=pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

In [4]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [5]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [6]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor

In [8]:
X = df.drop(columns=['price'])
y = df['price']

In [9]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

# Ordinal Encoding

In [10]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [11]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode)
    ], 
    remainder='passthrough'
)

In [12]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [13]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [14]:
scores.mean(),scores.std()

(np.float64(0.7363096633436828), np.float64(0.0323800575442993))

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [16]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [17]:
y_pred=pipeline.predict(X_test)

In [18]:
y_pred

array([1.15700081, 0.62935155, 0.78923869, 1.55827521, 1.37806207,
       1.53155016, 2.13474919, 1.23304871, 1.1204441 , 1.11267576,
       1.41235811, 0.71257546, 1.17963125, 0.94687144, 2.82323315,
       0.53201954, 0.61372621, 0.47943071, 0.75822332, 1.45440647,
       0.91377109, 0.80868333, 0.5414655 , 0.57317462, 1.01128127,
       1.23224246, 0.73995281, 0.4814698 , 0.91215684, 1.80808657,
       0.34147627, 0.68461037, 1.31543477, 0.47491893, 0.62086681,
       1.88091792, 0.77551852, 0.55149482, 0.5482935 , 0.38064681,
       0.67804879, 0.82079697, 0.45183075, 1.19277196, 1.19992839,
       0.38720351, 1.74781288, 0.91663109, 0.97387759, 1.1551884 ,
       0.99269947, 0.60040363, 1.54234043, 0.95755836, 0.94013957,
       0.34856039, 2.70521147, 1.67161834, 1.66305621, 1.00936094,
       1.1297326 , 1.2844578 , 0.5637419 , 0.77588884, 0.3702542 ,
       1.03630085, 0.8251405 , 1.62536322, 0.60463535, 1.0252044 ,
       1.13906142, 0.59046895, 0.93467746, 0.9488749 , 1.0967012 ,
       0.64099523, 1.00663449, 1.26030291, 0.42534486, 1.23301345,
       0.79846585, 0.86485853, 0.52509959, 0.69031825, 1.37093177,
       0.97401602, 0.37355535, 0.73646417, 0.84169819, 0.95151967,
       1.11493105, 0.77620715, 0.64934974, 0.76714439, 0.46637986,
       1.02098683, 1.24177077, 0.73284721, 0.65332093, 3.05678121,
       0.98066097, 2.20567321, 1.11435964, 0.78055077, 0.98895958,
       1.00428773, 0.60955159, 1.07402141, 1.0747463 , 0.89035737,
       1.31381619, 1.828869  , 0.70184776, 0.36743172, 0.84808118,
       0.52144761, 0.69578207, 0.90342391, 0.58648134, 0.67675069,
       0.80525741, 1.02956592, 0.93879577, 1.24261266, 0.73268755,
       0.88859246, 0.83635501, 1.17554953, 0.83926923, 0.73485896,
       0.73541509, 0.94411732, 0.45390739, 0.87296071, 0.38718257,
       1.30782056, 1.00102849, 2.30552329, 2.79241499, 0.77163807,
       1.68429531, 0.48627943, 1.48144336, 0.97127658, 0.70992329,
       0.56752849, 1.51162125, 1.10713483, 0.78067574, 0.72673764,
       0.66312474, 0.62874059, 1.4880146 , 0.73284721, 0.95088663,
       0.61849887, 1.08637087, 0.46952642, 1.40376957, 1.75237129,
       0.6638828 , 1.14473712, 0.66623484, 2.05686479, 0.80803833,
       1.75217716, 0.85903673, 0.82882054, 1.06888521, 0.90798348,
       1.1849558 , 0.78373579, 1.75992044, 0.79138766, 1.97543095,
       0.99306096, 0.93344182, 1.36803829, 0.5482466 , 0.72080273,
       0.67130893, 1.23621414, 1.22300687, 0.89336232, 1.60440845,
       0.82926431, 1.1810864 , 0.52713553, 0.66755966, 0.78331265,
       1.05567375, 0.97646383, 1.11934508, 1.36608364, 0.67653953,
       0.72564506, 0.76891307, 0.41047174, 0.71314994, 0.55961106,
       0.88621448, 0.51070476, 1.39023471, 0.4626652 , 1.69618626,
       0.98360806, 0.72017935, 0.99067411, 0.75107338, 0.87808575,
       0.63533815, 0.33108304, 1.41303487, 1.22204006, 1.36836465,
       0.63527485, 1.39126517, 0.61692256, 1.47599715, 1.09796696,
       1.21520881, 0.46307635, 0.83929379, 0.64183145, 0.69511002,
       1.25126806, 0.89405212, 1.09420845, 0.95289891, 1.55871147,
       0.85391215, 0.84964189, 1.84222819, 1.72733835, 0.61583025,
       1.04745036, 0.99136621, 1.2356503 , 1.1271432 , 1.20493313,
       0.97269301, 1.11674794, 1.07720056, 1.20865109, 1.92966126,
       1.13530202, 0.65720627, 1.02096571, 1.14013172, 0.82211523,
       0.40435303, 0.79443208, 1.67880555, 0.59911675, 0.90342165,
       0.93011848, 2.09745319, 0.60812249, 2.38067556, 1.10695364,
       0.85036968, 2.14547123, 0.86960448, 1.9139706 , 0.80636899,
       0.63587631, 0.69257341, 1.77962089, 2.04030963, 1.91784604,
       0.90746778, 1.29855254, 1.49844756, 0.75380136, 0.7011893 ,
       0.66913109, 0.63234701, 1.76847022, 1.14143127, 1.80919503,
       0.54236241, 0.69348141, 0.79784662, 0.91669696, 0.84130303,
       1.02281128, 1.22655971, 0.41787623, 1.27313941, 0.8614038 ,
       0.49157958, 1.60636616, 0.59660214, 0.60259596, 0.57619021,
       0.83141835, 0.37878513, 1.05575148, 1.01049388, 0.65127223,
       1.82350771, 1.13112447, 0.62167597, 1.54682288, 0.99575581,
       0.81458737, 1.07776058, 1.00806553, 0.97447261, 0.77632901,
       1.45853214, 0.70857509, 0.73274667, 0.78031942, 0.64070137,
       0.72355123, 0.75095773, 0.95751445, 0.69580919, 1.10906874,
       1.47813573, 0.65568995, 2.31407127, 0.52674263, 1.77585063,
       0.96900771, 1.74990414, 1.09918113, 1.43585809, 0.62032972,
       0.58348013, 0.89893368, 1.0092797 , 2.0375336 , 0.63909399,
       3.33599633, 1.68832934, 1.19447649, 0.68668778, 1.02540974,
       0.98792588, 0.9194832 , 0.90547114, 0.77201357, 1.31490383,
       0.68471535, 0.87399134, 0.61192466, 0.52680605, 0.81427788,
       1.21569772, 0.93148581, 2.36253608, 1.28655677, 1.16089378,
       0.97628274, 1.35578325, 1.23897847, 0.69898111, 0.34445928,
       1.43466986, 1.29196348, 0.88296874, 1.09442723, 0.83632328,
       1.34602174, 1.32132924, 0.73887131, 1.37069129, 0.70887208,
       1.12337003, 1.26710121, 0.92782995, 0.66871371, 0.49801379,
       1.9220983 , 1.18115475, 1.0471501 , 0.77845014, 0.63110632,
       0.7142499 , 1.22299054, 1.85863044, 0.62494175, 0.34368165,
       0.88771026, 1.23396302, 1.02359069, 0.44501707, 1.24756141,
       0.96709286, 0.65672166, 0.75996992, 0.7278241 , 1.08934072,
       1.01976526, 1.54072281, 1.08188737, 1.90485468, 1.04912001,
       0.97644115, 1.14065663, 0.31140833, 0.57686684, 1.02925726,
       0.5728046 , 1.16404758, 0.88054483, 0.76523022, 1.24007558,
       0.79651058, 2.20669672, 0.66166461, 1.10405424, 0.79906466,
       2.00302924, 0.49484824, 1.07612385, 0.40373119, 0.45478324,
       0.73527556, 0.69220621, 0.47913608, 1.12863079, 1.79050089,
       0.27485803, 0.78627773, 2.69137755, 1.46297109, 0.77711071,
       1.84618618, 0.53968054, 1.6277143 , 0.67619131, 0.75411445,
       1.76934822, 0.7498592 , 2.18442993, 0.70452327, 1.26864732,
       1.00105861, 0.78801485, 0.41620642, 0.78461131, 1.65122854,
       0.88077699, 0.44954373, 1.17564226, 1.99150976, 1.52150773,
       0.7015764 , 0.730605  , 0.8967728 , 1.25631199, 0.95694702,
       1.1211938 , 0.75823746, 0.96884971, 0.86215272, 0.59491751,
       0.78852091, 1.5220916 , 1.53324386, 0.81346337, 1.06686559,
       1.29563722, 0.84886456, 0.95465454, 0.8638035 , 0.65483564,
       0.4844767 , 2.64022637, 0.50876034, 0.30652394, 2.19279914,
       1.75074887, 0.70412839, 0.68283212, 0.78951201, 1.45120453,
       1.33403586, 1.47119673, 0.61704442, 1.02221454, 1.0050383 ,
       1.24168819, 1.74437902, 0.46801259, 1.45006189, 0.86878265,
       2.15883023, 1.05740305, 1.24207602, 1.14828362, 2.44670513,
       3.47054884, 0.66623484, 1.08385011, 1.09874479, 0.67009801,
       1.54169535, 0.49905225, 0.73582824, 0.84907727, 2.54230486,
       0.77211539, 1.20532036, 1.57707963, 0.45934418, 0.71034446,
       0.76924111, 0.99171262, 1.71463936, 0.72443089, 0.90135022,
       0.91691768, 1.06739682, 0.73170572, 0.84973152, 0.81308064,
       0.60239317, 1.82607472, 0.68345506, 0.61722268, 1.43312962,
       0.71970766, 0.60614338, 0.36308619, 0.75773464, 0.72236307,
       1.44469892, 0.40346057, 0.78461131, 0.84053124, 0.90920841,
       0.96661644, 0.89411346, 1.93126713, 1.28542392, 0.72560433,
       1.43976367, 0.68803285, 1.17750134, 1.35108716, 0.97615482,
       0.4571326 , 0.3971148 , 0.26915927, 1.04485996, 1.46840721,
       0.91600235, 0.79974201, 0.88458763, 0.69444226, 0.69664369,
       0.45679701, 0.77895861, 1.0478932 , 2.75788424, 2.02519272,
       0.7002496 , 0.66306675, 1.08229045, 1.31129397, 1.0441059 ,
       0.75319217, 0.67801556, 0.96108336, 1.95063708, 2.44084832,
       1.27156351, 0.76371207, 1.00800615, 2.39288666, 2.26304751,
       1.88526296, 1.3855147 , 0.60048711, 0.66231702, 1.36655775,
       0.93281331, 0.43661506, 0.76775967, 0.37997505, 1.06621106,
       1.50669837, 0.58531531, 1.0895076 , 0.5375828 , 0.69535288,
       1.03242549, 2.28705488, 0.59970227, 1.19277057, 0.69915716,
       0.5128683 , 0.71671789, 0.44213664, 0.78706704, 0.94065145,
       1.22780332, 0.74915499, 0.73875243, 1.00806553, 0.56636459,
       1.54555344, 1.18877434, 0.54027848, 0.66749954, 0.97697161,
       1.13839736, 0.77744744, 1.07236569, 0.62698934, 0.54609376,
       0.95738914, 1.19376079, 1.2185384 , 0.92669728, 0.50817078,
       1.02971422, 1.52046026, 1.66166788, 1.43388016, 0.62203936,
       0.83637815, 0.87590192, 0.64810136, 2.91568239, 0.82946978,
       0.80316391, 0.47210035, 0.28472757, 0.80176468, 0.71776136,
       0.90920841, 0.61150231, 1.19014437, 1.13450003, 0.72051706,
       1.32772419, 0.83978359, 1.25703539, 0.58366257, 1.13093171,
       0.9540177 , 2.19279914, 1.2978045 , 2.50121837, 1.13806725,
       0.36606107, 1.29107337, 1.28213264, 0.38728118, 1.60667259,
       1.56984245, 0.52740745, 1.11955135, 1.1575338 , 0.66599718,
       1.1216951 , 0.83874294, 0.64323109, 0.8660874 , 0.68828076,
       0.55942001, 0.79047878, 0.85161784, 2.80745868, 0.64636209,
       0.4706706 , 3.14553294, 1.18930885, 0.85378099, 3.51682999,
       0.75466913, 0.89293835, 1.1065885 , 1.53394574, 1.29807247,
       0.45650517, 2.10566679, 2.26255492, 0.83499205, 0.76491325,
       0.41153602, 0.86185656, 0.61692256, 1.19311241, 0.67294985,
       0.85570802, 1.19536683, 0.42027541, 0.97616088, 1.62615436,
       1.21723525, 0.55511944, 1.23806755, 2.02199787, 0.56414438,
       1.26835537, 0.62653831, 1.20299285, 1.04139059, 0.92366029,
       0.9018326 , 0.52650816, 0.95271839, 1.06054413, 0.77676208,
       0.78133081])

In [19]:
y_pred=np.expm1(y_pred)

In [21]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.946382216008936

In [49]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [50]:
model_dict={
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree':DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees':ExtraTreesRegressor(),
    'gradient boosting':GradientBoostingRegressor(),
    'adaboost':AdaBoostRegressor(),
    'mlp':MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [51]:
model_output=[]
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name,model))

In [52]:
model_output

[['linear_reg', np.float64(0.7363096633436828), 0.946382216008936],
 ['svr', np.float64(0.7642012011196353), 0.847263647348393],
 ['ridge', np.float64(0.7363125343993554), 0.9463387741853386],
 ['LASSO', np.float64(0.05943378064493573), 1.528905986892753],
 ['decision tree', np.float64(0.7712158758154087), 0.723633553363332],
 ['random forest', np.float64(0.8800647189821922), 0.5239854154697426],
 ['extra trees', np.float64(0.8686757134153765), 0.5483396916898954],
 ['gradient boosting', np.float64(0.8726245244442075), 0.5757695812151836],
 ['adaboost', np.float64(0.7580189621222422), 0.8484280255873988],
 ['mlp', np.float64(0.810902540785101), 0.6519914154876478],
 ['xgboost', np.float64(0.8894876835260124), 0.5040475141482346]]

In [53]:
model_df=pd.DataFrame(model_output,columns=['name','re','mae'])

In [55]:
model_df.sort_values(['mae'])

                 name        re       mae
10            xgboost  0.889488  0.504048
5       random forest  0.880065  0.523985
6         extra trees  0.868676  0.548340
7   gradient boosting  0.872625  0.575770
9                 mlp  0.810903  0.651991
4       decision tree  0.771216  0.723634
1                 svr  0.764201  0.847264
8            adaboost  0.758019  0.848428
2               ridge  0.736313  0.946339
0          linear_reg  0.736310  0.946382
3               LASSO  0.059434  1.528906

# OneHotEncoding

In [56]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first'),['sector','agePossession','furnishing_type'])
    ], 
    remainder='passthrough'
)

In [57]:
# Creating a pipeline
pipeline =Pipeline([
    ('preprocessor',preprocessor),
    ('regressor',LinearRegression())
])

In [58]:
# k-fold cross- validation
kfold=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(pipeline,X,y_transformed,cv=kfold,scoring='r2')

In [59]:
scores.mean()

np.float64(0.8546067827628422)

In [60]:
scores.std()

np.float64(0.015998393588058008)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [62]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first'),
                                                  ['sector', 'agePossession',
                                                   'furnishing_type'])])),
                ('regressor', LinearRegression())])

In [63]:
y_pred=pipeline.predict(X_test)

In [64]:
y_pred

array([0.95937553, 0.44532388, 0.78013825, 1.33064163, 1.29956591,
       1.39143106, 2.19140301, 1.03928307, 1.02130638, 1.00045183,
       1.3434242 , 0.73909013, 1.35086417, 0.92081199, 2.91813903,
       0.51234444, 1.16488443, 0.31029886, 0.63482305, 1.33203635,
       0.81985486, 0.83095419, 0.58488368, 0.73797908, 1.03890619,
       1.5090816 , 0.54347447, 0.57351423, 0.7263091 , 2.17998772,
       0.3470468 , 0.46693396, 1.61387478, 0.33067807, 0.6703607 ,
       1.62822306, 0.96360972, 0.50894059, 0.43089769, 0.32720833,
       0.51080815, 1.1112027 , 0.42947945, 1.03554695, 1.00044085,
       0.44748243, 1.841439  , 1.00327422, 1.14772266, 0.97870748,
       0.97158293, 0.5073988 , 1.79852358, 1.15309161, 0.73014389,
       1.00949951, 2.50605624, 1.41929253, 1.77347823, 0.98911963,
       0.95622572, 1.417949  , 0.49275577, 1.46282893, 0.28867638,
       1.03923191, 1.37972553, 1.32164774, 0.43519705, 0.80397749,
       1.35272299, 0.58534716, 1.01968817, 1.11286928, 1.42137464,
       0.45469029, 1.43850506, 1.04307429, 0.37301848, 1.42666053,
       0.7658418 , 0.82722865, 0.37142531, 0.65710865, 1.55919184,
       1.05014699, 0.17431246, 0.54062068, 0.75569896, 0.82793705,
       0.99690743, 1.13042511, 0.86978955, 0.77400117, 0.31619546,
       1.06841184, 1.01418059, 0.84070842, 0.68033375, 3.03754389,
       0.9555478 , 1.95260265, 1.03677377, 0.60578735, 1.09358562,
       0.97282841, 0.7355349 , 0.97331542, 0.84284585, 0.90568899,
       1.0961328 , 1.65408918, 0.68703087, 0.55009917, 0.66117056,
       0.47064446, 0.68075961, 0.80274231, 0.68433933, 0.68015054,
       0.86085432, 0.87654501, 1.31187304, 1.19103744, 0.59317314,
       0.81009796, 0.79813204, 1.31181088, 0.72878622, 0.59605893,
       0.63211489, 0.95602301, 0.56424404, 0.86592622, 0.3525102 ,
       1.281847  , 0.83881752, 2.12395871, 3.06551918, 0.57835183,
       1.37736126, 0.38212948, 1.40463743, 0.85795595, 0.72340575,
       0.40290168, 1.44389353, 1.83847738, 0.51083094, 0.94925656,
       0.75091073, 0.6607325 , 1.7524909 , 0.84070842, 0.79371294,
       0.69952992, 1.03960418, 0.29268957, 1.64741399, 1.79753292,
       0.7624289 , 0.95558685, 0.7834244 , 2.13599963, 0.81485517,
       1.57478851, 1.00553795, 0.6604554 , 0.97600289, 1.35839208,
       1.29991329, 0.62370859, 2.11866263, 0.61755855, 2.06268486,
       0.92190027, 0.89431013, 1.09891501, 0.60717782, 0.58467012,
       0.59817001, 1.16445095, 1.38330618, 0.79341902, 1.55561924,
       0.77058404, 0.9248325 , 0.43979443, 0.73473293, 0.72156444,
       0.84821141, 0.89417192, 0.98984692, 1.51473278, 0.74377373,
       0.74037704, 0.78236298, 0.3884298 , 0.73249375, 0.35139905,
       0.82170406, 0.57897098, 1.39733053, 0.32052436, 1.57809646,
       1.05838039, 0.83276389, 1.25023613, 0.85813697, 0.64382936,
       0.70717554, 0.38705447, 1.95737713, 1.50202592, 1.59032469,
       0.62304031, 0.97134905, 0.98857836, 1.82166558, 0.67094479,
       1.5126865 , 0.5409332 , 0.93414286, 0.72277714, 0.63637403,
       1.36572946, 0.71959326, 0.69861038, 0.98014962, 1.26457696,
       0.70283758, 0.84037122, 2.07911646, 2.10177373, 0.95281631,
       0.84121477, 0.86052084, 1.15439808, 0.82378995, 1.1504816 ,
       0.79238814, 0.91961689, 0.84483438, 1.05143881, 2.12161366,
       0.95734244, 0.68234587, 1.65958435, 1.02454705, 1.16165747,
       0.31661892, 1.21933261, 1.50825917, 0.6483945 , 0.93835822,
       0.69256399, 2.18831924, 0.98055216, 2.40479247, 1.18899684,
       0.64628135, 2.10753165, 0.80902939, 1.97999792, 0.84225845,
       0.7243668 , 0.72787821, 2.15837435, 1.84843987, 1.60264738,
       0.95664872, 1.39940224, 1.54120164, 0.52809101, 0.58638507,
       0.50685998, 0.48767774, 2.03506348, 1.09279443, 2.07544748,
       0.42754258, 0.76068559, 1.11487328, 0.92025479, 0.74869395,
       0.8449055 , 1.12655366, 0.32815741, 1.53462658, 0.68701437,
       0.63066197, 1.6888425 , 0.2986062 , 0.62141896, 0.42636962,
       0.91406669, 0.21169807, 0.72921297, 0.96576294, 0.67615192,
       1.69694308, 0.97794508, 0.6811793 , 1.74596784, 0.86046472,
       0.96836053, 0.67162574, 0.96200323, 1.36158412, 1.09654291,
       1.27929603, 0.79347743, 1.27505703, 0.83693276, 0.7514582 ,
       0.55925503, 0.58757587, 0.61416354, 0.72000005, 0.90198843,
       1.59361046, 0.43726569, 2.09561431, 0.39792727, 1.6734333 ,
       0.85643218, 1.95888998, 0.67282465, 1.32744472, 0.45091387,
       0.670957  , 1.27894636, 0.96388309, 1.50208914, 0.71311957,
       2.7319385 , 1.55414336, 1.36271393, 0.50612983, 1.14241279,
       1.01601809, 1.11798072, 1.3072208 , 0.69603582, 1.408618  ,
       1.17140798, 1.16981348, 0.48274112, 0.37182264, 1.30908485,
       1.4640691 , 1.11337543, 2.46788407, 1.02948694, 1.5337984 ,
       0.8322968 , 1.72784424, 1.22560372, 0.76050618, 0.46925754,
       1.80086076, 1.54322996, 1.0490944 , 1.0324057 , 0.78496479,
       1.58022442, 1.21041102, 0.84558934, 1.58327162, 0.78002188,
       1.02624969, 1.39315431, 0.94282645, 0.69715031, 0.61645201,
       1.99734224, 1.368436  , 0.97523295, 0.48327542, 0.38338072,
       0.87731181, 0.9850225 , 1.55837414, 0.54604141, 0.49121241,
       0.67411493, 1.16652672, 0.80478971, 0.62342454, 1.17484061,
       0.83631412, 1.02707733, 0.97470481, 0.56901037, 0.86368197,
       0.86218211, 1.76936249, 0.76138099, 2.2261778 , 0.86118265,
       0.80702034, 1.12211084, 0.22530747, 0.5149654 , 0.63317343,
       0.45310395, 1.05860585, 0.76186323, 0.62248143, 1.14089616,
       1.14687562, 2.44650981, 0.49515286, 1.25298694, 0.57732729,
       2.08076704, 0.37522444, 0.77573789, 0.38633397, 0.44607243,
       0.84446814, 0.66626704, 0.85214106, 0.95499423, 1.81123967,
       0.37401618, 0.90460035, 2.59729553, 1.41472671, 0.87599062,
       1.68019437, 0.69230471, 1.87006809, 1.03581932, 0.83338638,
       2.00691972, 0.85625711, 2.00031202, 0.61630283, 1.11882281,
       0.89289747, 0.58128001, 0.63551259, 0.67907154, 2.2250264 ,
       0.90823343, 0.80171722, 1.16294717, 2.27816883, 1.78937477,
       0.92524428, 0.7691702 , 1.28504344, 0.99623096, 0.92058532,
       1.12524695, 0.8827201 , 0.96136816, 0.64532707, 0.43080581,
       0.77651212, 1.20172188, 1.42227263, 0.72845673, 1.17571432,
       1.30966485, 0.90213538, 0.98485289, 0.80432924, 0.3161417 ,
       0.29064338, 2.35943301, 0.48904656, 0.36206002, 2.07414182,
       1.84496027, 1.12275883, 0.79629052, 0.65538644, 1.25660675,
       1.47341581, 1.6053929 , 0.95469617, 1.30610195, 0.9016912 ,
       1.12462338, 1.61714383, 0.43484532, 1.89649038, 0.91948431,
       2.33946082, 0.82872446, 1.47772212, 1.39101496, 2.02879243,
       3.06705014, 0.7834244 , 1.06279784, 1.1407779 , 0.4255411 ,
       1.16458532, 0.39424345, 1.09699103, 0.65870877, 2.52350197,
       0.8725248 , 1.41733785, 1.94793764, 0.29199208, 0.95852791,
       0.65751702, 1.30375383, 1.79968449, 0.73849718, 1.28121887,
       0.9306683 , 0.90630076, 0.84157574, 0.70217251, 0.78403706,
       0.46639829, 1.91272198, 0.70586469, 1.14631309, 1.42195675,
       0.49118038, 0.61096565, 0.33298651, 0.8227859 , 0.8827019 ,
       1.22287987, 0.31589582, 0.67907154, 1.09108511, 0.94881821,
       0.88125281, 0.90338018, 1.74029429, 0.84616253, 0.787267  ,
       1.57442116, 0.71920489, 1.51383612, 1.15190489, 0.76527143,
       0.35848658, 0.33505607, 0.22004363, 1.01843549, 1.61431672,
       1.05379449, 0.64949824, 0.92423419, 1.14240091, 0.62666305,
       0.39424983, 0.67770701, 0.94241281, 2.45596785, 2.15769912,
       0.74309761, 0.63737515, 1.02782896, 1.22676026, 1.15608535,
       0.69715983, 0.5823592 , 0.64030217, 1.66173066, 2.18885785,
       1.17262514, 0.71775882, 0.76737744, 2.42143035, 2.60565834,
       1.89942946, 1.48439177, 0.50710175, 0.39773722, 1.17426605,
       0.97539547, 0.50176393, 0.61481365, 0.60673829, 1.00710982,
       1.58874412, 0.49480906, 0.82909816, 0.56932469, 0.74060777,
       0.79517077, 2.53841329, 0.47141485, 1.46016727, 0.76342974,
       0.25487148, 0.68555731, 0.65509883, 0.7982795 , 0.68469962,
       1.18163241, 1.10674155, 0.7666871 , 0.96200323, 0.59264465,
       1.42240175, 0.99710236, 0.84253071, 0.69527045, 0.84720188,
       0.94640669, 0.66558934, 1.06096637, 0.49554004, 0.46194469,
       0.76306683, 1.12382974, 1.1478101 , 0.81314633, 0.42442857,
       1.07369087, 1.23268847, 1.60883476, 1.3711379 , 0.51610711,
       1.12931351, 0.50912045, 0.50102398, 2.6934072 , 1.17229312,
       0.85486057, 0.41000522, 0.2051403 , 0.84766018, 0.67934396,
       0.94881821, 0.71538523, 1.00384225, 1.04104663, 0.61820762,
       1.64861692, 0.72653418, 1.41281967, 0.41820421, 1.52348409,
       0.66298055, 2.07414182, 1.4446415 , 2.73487047, 0.97518236,
       0.2969033 , 1.49524782, 1.15746141, 0.35348618, 1.46562599,
       1.45833827, 0.54997279, 1.02893472, 0.87591986, 0.73793875,
       1.06662341, 0.65180009, 0.58995542, 0.97407182, 0.73495942,
       0.3969902 , 0.78024692, 0.93400288, 2.78972463, 0.54600901,
       0.56771645, 3.20573265, 1.1200044 , 0.81285523, 3.40328822,
       0.85925817, 1.34209529, 1.1628768 , 1.24451095, 1.86849264,
       0.29348885, 2.20194838, 2.53098802, 0.97224016, 0.77219342,
       0.3215699 , 0.94496906, 0.98857836, 0.74893087, 0.56465036,
       1.10602767, 1.15095893, 0.35469048, 0.84879827, 1.27271073,
       1.00954083, 0.36880952, 1.13926918, 2.34848864, 0.48907613,
       1.60806631, 0.452629  , 1.13917503, 0.90230008, 0.91219637,
       0.89806015, 0.686849  , 0.65173374, 0.98708509, 0.52317329,
       1.13516454])

In [65]:
y_pred=np.expm1(y_pred)

In [66]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.6497458331374444

In [67]:
def scorer(model_name,model):

    output=[]

    output.append(model_name)

    pipeline=Pipeline([
        ('preprocessor',preprocessor),
        ('regressor',model)
    ])

    # K-fold cross validation
    kfold=KFold(n_splits=10,shuffle=True,random_state=42)
    scores=cross_val_score(pipeline,X,y_transformed,cv=kfold,scoring='r2')

    output.append(scores.mean())

    X_train,X_test,y_train,y_test=train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred=pipeline.predict(X_test)

    y_pred=np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    return output

In [68]:
model_dict={
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree':DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra tress':ExtraTreesRegressor(),
    'gradient boosting':GradientBoostingRegressor(),
    'adaboost':AdaBoostRegressor(),
    'mlp':MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [69]:
model_output=[]
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name,model))

In [70]:
model_df=pd.DataFrame(model_output,columns=['name','r2','mae'])

In [71]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra tress  0.894944  0.462849
10            xgboost  0.895850  0.493456
5       random forest  0.889222  0.503045
7   gradient boosting  0.876520  0.569743
0          linear_reg  0.854607  0.649746
2               ridge  0.854687  0.652831
9                 mlp  0.865989  0.670205
4       decision tree  0.805710  0.704327
1                 svr  0.769741  0.834124
8            adaboost  0.749977  0.843525
3               LASSO  0.059434  1.528906

# OneHotEncoding With PCA

In [72]:
# creating a column transformer for preprocessing
preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),['bedRoom','bathroom','built_up_area','servant room','store room']),
        ('cat',OrdinalEncoder(),columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ],
    remainder='passthrough'
)

In [74]:
# creating a pipeline
pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('pca',PCA(n_components=0.95)),
    ('regressor',LinearRegression())
])

In [75]:
kfold=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(pipeline,X,y_transformed,cv=kfold,scoring='r2')

In [76]:
scores.mean()

np.float64(0.06225201431451137)

In [77]:
scores.std()

np.float64(0.019860594071640165)

In [82]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [83]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [84]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [85]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [86]:
model_df.sort_values(['mae'])

                 name        r2       mae
5       random forest  0.763105  0.646462
6         extra trees  0.739286  0.694413
4       decision tree  0.696442  0.761509
10            xgboost  0.622205  0.967581
7   gradient boosting  0.610623  0.987906
1                 svr  0.218073  1.361163
9                 mlp  0.212399  1.417098
8            adaboost  0.309748  1.443715
2               ridge  0.062252  1.526707
0          linear_reg  0.062252  1.526707
3               LASSO  0.059676  1.528739

# Target Encoder

In [97]:
import category_encoders as ce

columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [87]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\user\anaconda3\lib\site-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in c:\users\user\anaconda3\lib\site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\user\anaconda3\lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\user\anaconda3\lib\site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\user\anaconda3\lib\site-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\user\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [98]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [99]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [100]:
scores.mean(),scores.std()

(np.float64(0.829521918225536), np.float64(0.01838446337912288))

In [101]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [102]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [103]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [104]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [105]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.904798  0.447518
6         extra trees  0.901472  0.454966
5       random forest  0.901643  0.458587
7   gradient boosting  0.888788  0.509227
4       decision tree  0.830769  0.568428
9                 mlp  0.849414  0.641170
8            adaboost  0.814898  0.676855
0          linear_reg  0.829522  0.713011
2               ridge  0.829536  0.713523
1                 svr  0.782917  0.818851
3               LASSO  0.059434  1.528906

# HyperParameter Tunning

In [106]:
from sklearn.model_selection import GridSearchCV

In [114]:
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': ['auto', 'sqrt']
}

In [115]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [116]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor())
])

In [117]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [118]:
search = GridSearchCV(pipeline, param_grid, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [119]:
search.fit(X, y_transformed)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
640 fits failed out of a total of 1280.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
379 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 662, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
261 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 662, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.86902567 0.86991932
 0.87320096 0.87312254 0.88461409 0.88673428 0.88850839 0.88657416
 0.89130376 0.89572408 0.89690491 0.89634516 0.89957786 0.90217975
 0.90210004 0.90240983        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.86774604 0.86984803 0.86999051 0.87193448 0.87947431 0.88438271
 0.88344434 0.88394903 0.88613518 0.88989346 0.88950113 0.88992038
 0.89024625 0.89236554 0.8935416  0.8938149         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.86844515 0.87185896 0.87147763 0.87232939
 0.88425027 0.8861811  0.88811225 0.88883975 0.89429663 0.89573723
 0.89584777 0.8965502  0.89964692 0.90099591 0.9020747  0.90218394
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.86714384 0.87067154
 0.87161995 0.87316293 0.88421982 0.88784661 0.88884088 0.88873071
 0.89286752 0.89536977 0.89680329 0.89741982 0.89990673 0.9014344
 0.90190404 0.90235335]
  warnings.warn(

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedRoom',
                                                                          'bathroom',
                                                                          'built_up_area',
                                                                          'servant '
                                                                          'room',
                                                                          'store '
                                                                          'room']),
                                                                        ('cat',
                                                                         OrdinalEncoder(),
                                                                         ['property_type',
                                                                          'sector',
                                                                          'balcony',
                                                                          'agePossession',
                                                                          'furnishing_type',...
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         ['agePossession']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['sector'])])),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=-1,
             param_grid={'regressor__max_depth': [None, 10, 20, 30],
                         'regressor__max_features': ['auto', 'sqrt'],
                         'regressor__max_samples': [0.1, 0.25, 0.5, 1.0],
                         'regressor__n_estimators': [50, 100, 200, 300]},
             scoring='r2', verbose=4)

In [120]:
final_pipe = search.best_estimator_

In [121]:
final_pipe

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePossession']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_features='sqrt', max_samples=1.0,
                                       n_estimators=300))])

In [122]:
search.best_params_

{'regressor__max_depth': None,
 'regressor__max_features': 'sqrt',
 'regressor__max_samples': 1.0,
 'regressor__n_estimators': 300}

In [123]:
search.best_score_

np.float64(0.902409832351767)

In [124]:
final_pipe.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePossession']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_features='sqrt', max_samples=1.0,
                                       n_estimators=300))])

In [125]:
search.best_score_

np.float64(0.902409832351767)

# Exporting The model

In [129]:
preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),['bedRoom','bathroom','built_up_area','servant room','store room']),
        ('cat',OrdinalEncoder(),columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ],
    remainder='passthrough'
)

In [130]:
pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('regressor',RandomForestRegressor(n_estimators=500))
])

In [131]:
pipeline.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sector',
                                                   'agePossession'])])),
                ('regressor', RandomForestRegressor(n_estimators=500))])

In [132]:
import pickle

with open('df.pkl','wb') as file:
    pickle.dump(X,file)

In [133]:
X

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,2.0,2.0,1,Relatively New,532.0,0.0,0.0,unfurnished,Medium,Mid Floor
3550,house,sector 109,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,unfurnished,High,Low Floor
3551,flat,sector 2,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,semifurnished,Medium,Mid Floor
3552,house,sector 43,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,unfurnished,Medium,Mid Floor
3553,flat,sector 68,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,semifurnished,Medium,High Floor

In [134]:
with open('pipeline.pkl','wb') as file:
    pickle.dump(pipeline,file)

In [ ]:
# Trying out the Predictions

In [135]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='object')

In [136]:
X.iloc[0].values

array(['flat', 'sector 36', np.float64(3.0), np.float64(2.0), '2',
       'New Property', np.float64(850.0), np.float64(0.0),
       np.float64(0.0), 'unfurnished', 'Low', 'Low Floor'], dtype=object)

In [137]:
data=[['house','sector 102',4,3,'3+','New Property',2750,0,0,'unfurnished','Low','Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']
# Convert to DataFrame
one_df = pd.DataFrame(data, columns=columns)

one_df

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,house,sector 102,4,3,3+,New Property,2750,0,0,unfurnished,Low,Low Floor

In [138]:
np.expm1(pipeline.predict(one_df))

array([3.19791933])

In [139]:
X.dtypes

property_type       object
sector              object
bedRoom            float64
bathroom           float64
balcony             object
agePossession       object
built_up_area      float64
servant room       float64
store room         float64
furnishing_type     object
luxury_category     object
floor_category      object
dtype: object

In [140]:
sorted(X['sector'].unique().tolist())

['dwarka expressway',
 'gwal pahari',
 'manesar',
 'sector 1',
 'sector 10',
 'sector 102',
 'sector 103',
 'sector 104',
 'sector 105',
 'sector 106',
 'sector 107',
 'sector 108',
 'sector 109',
 'sector 11',
 'sector 110',
 'sector 111',
 'sector 112',
 'sector 113',
 'sector 12',
 'sector 13',
 'sector 14',
 'sector 15',
 'sector 17',
 'sector 2',
 'sector 21',
 'sector 22',
 'sector 23',
 'sector 24',
 'sector 25',
 'sector 26',
 'sector 27',
 'sector 28',
 'sector 3',
 'sector 30',
 'sector 31',
 'sector 33',
 'sector 36',
 'sector 37',
 'sector 37d',
 'sector 38',
 'sector 39',
 'sector 4',
 'sector 40',
 'sector 41',
 'sector 43',
 'sector 45',
 'sector 46',
 'sector 47',
 'sector 48',
 'sector 49',
 'sector 5',
 'sector 50',
 'sector 51',
 'sector 52',
 'sector 53',
 'sector 54',
 'sector 55',
 'sector 56',
 'sector 57',
 'sector 58',
 'sector 59',
 'sector 6',
 'sector 60',
 'sector 61',
 'sector 62',
 'sector 63',
 'sector 63a',
 'sector 65',
 'sector 66',
 'sector 67',
 'sector 67a',
 'sector 68',
 'sector 69',
 'sector 7',
 'sector 70',
 'sector 70a',
 'sector 71',
 'sector 72',
 'sector 73',
 'sector 74',
 'sector 76',
 'sector 77',
 'sector 78',
 'sector 79',
 'sector 8',
 'sector 80',
 'sector 81',
 'sector 82',
 'sector 82a',
 'sector 83',
 'sector 84',
 'sector 85',
 'sector 86',
 'sector 88',
 'sector 88a',
 'sector 89',
 'sector 9',
 'sector 90',
 'sector 91',
 'sector 92',
 'sector 93',
 'sector 95',
 'sector 99',
 'sohna road']